apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: kind
    devEnvApprovers:
    - cicd-breqwatr
    environmentGitOwner: cicd-breqwatr
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: cicd-breqwatr
    repository: jx3-kubernetes-cluster
  - key: staging
  - key: production
  ingress:
<<<<<<< HEAD
    domain: 10.106.250.2
=======
    domain: 10.106.250.3.nip.io
>>>>>>> 382855779fb594a9e55e9ce78bf709c989c0f02e
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: cicd-breqwatr
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
